# Site settings
name                : ᵇᵒ
email               : 40080007@qq.com
author              : ᵇᵒ
url                 : https://y4n9b0.github.io/
resume_site         : https://y4n9b0.github.io/author
github              : https://github.com/y4n9b0/
baseurl             : ""
banner              : Fear springs from ignorance.

#gems
gems                : [jekyll-paginate,jemoji]

permalink           : /:year/:month/:day/:title/
paginate            : 10

exclude             : ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username     : y4n9b0
highlighter         : rouge

# Build settings
markdown            : kramdown

baidu_analysis      : 94be4b0f9fc5d94cc0d0415ea6761ae9

comments:
    provider        : gitalk
    #duoshuo    :
    #   short_name  : xxx
    #disqus     :
    #   short_name  : xxx
    #facebook   :
    #   appid       : 123
    #   num_posts   : 5
    #   width       : 580
    #   colorscheme : light
